spring.application.name=backend

# 디비
spring.datasource.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
spring.datasource.url=jdbc:log4jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=jeh
spring.datasource.password=1234

# react 스키마를 바라보도록 설정
spring.datasource.hikari.connection-init-sql=ALTER SESSION SET CURRENT_SCHEMA = react

# 서버 포트
server.port=8080

# 디버깅
logging.level.web=info

mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

# 전역 CORS 설정
cors.allowed-origin=http://localhost:5173

# jwt 설정
jwt.secret=change-this-to-a-long-random-secret-at-least-32-bytes